Add Swan:Arxiv22 to pub
SymbioticLab/SymbioticLab.github.io pull request #131
Opened 2022-06-21 04:07 UTC by singam-sanjay

2022-06-22 00:30 UTC, jaywonchung commented
@mosharaf This PR will introduce a new `publist_topic` "Mobile Systems". Sounds right, but FL papers until know didn't have that topic. WDYT?

2022-06-22 00:39 UTC, mosharaf commented
Remove it. We don't have that topic. Stick to the ones we have.

2022-06-22 00:40 UTC, mosharaf commented
Use Systems + AI and Wide-Area Computing

2022-06-22 00:41 UTC, jaywonchung requested changes

2022-06-22 00:41 UTC, jaywonchung commented on source/_data/SymbioticLab.bib
> +	  publist_topic = {Mobile Systems},
Refer to Mosharaf's comment

2022-07-03 00:55 UTC, singam-sanjay commented on source/_data/SymbioticLab.bib
> +	  publist_topic = {Mobile Systems},
@jaywonchung Please check it out.

2022-07-03 01:00 UTC, jaywonchung commented
@singam-sanjay I don't think the blogging system is smart enough to understand `publist_topic = {Systems + AI and Wide-Area Computing}`. Refer to the following:
https://github.com/SymbioticLab/SymbioticLab.github.io/blob/83bb3e5bdaa82d321a4f9afc55dd43751b4577ef/source/_data/SymbioticLab.bib#L964-L965

2022-07-03 19:09 UTC, singam-sanjay commented on source/_data/SymbioticLab.bib
> +	  publist_topic = {Mobile Systems},
I've separately listed the topics now.

2022-07-03 19:10 UTC, singam-sanjay commented
I've listed the topics separately now.

2022-07-03 19:11 UTC, jaywonchung approved these changes
LGTM

2022-07-03 19:11 UTC, merged