Add Chase to pubs
SymbioticLab/SymbioticLab.github.io pull request #178
Opened 2023-03-07 06:49 UTC by jaywonchung

This workshop is not under ICLR, but has its own org behind it (This year it's with ICLR, but last year it was with NeurIPS). That's why I made the venue key just `ClimateML` instead of something like `ClimateML-ICLR`.

#177 is to be kept open for the camera ready version, slides, and code.

2023-03-09 16:49 UTC, insujang requested changes
The official organization name and workshop name is Climate Change AI (CCAI). Maybe better to use it?

2023-03-09 16:49 UTC, insujang commented on source/publications/index.md
> +    - key: ClimateML-ICLR'23
```suggestion
  ClimateChangeAI:
    category: Workshops
    occurrences:
    - key: CCAI-ICLR'23
```

2023-03-09 16:49 UTC, insujang commented on source/_data/SymbioticLab.bib
> +  publist_confkey = {ClimateML-ICLR'23},
```suggestion
  publist_confkey = {CCAI-ICLR'23},
```

2023-03-09 17:22 UTC, jaywonchung commented
That's much better. Thanks for the suggestion! I've applied both.

2023-03-09 17:27 UTC, insujang approved these changes
LGTM

2023-03-09 17:33 UTC, merged

2023-03-10 03:06 UTC, mosharaf commented
If #177 is open, why did we merge this instead of the arxiv one?

2023-03-10 03:09 UTC, jaywonchung commented
This is the arXiv version. I added this quick and merged this PR to publish Chase to the list of publications as early as possible. I left #177 open to serve as a reminder to update the paper link to the official one when the workshop goes live.

2023-03-10 03:10 UTC, mosharaf commented
This should've been the arxiv link and not like this, like all other papers that have had arxiv versions. This is breaking the protocol that we've implicitly created re:arxiv and conference versions

2023-03-10 03:13 UTC, mosharaf commented
We have never uploaded a conference/workshop paper that's not camera-ready. Whenever we did early upload, they've always been arxiv separate from a later camera-ready version

2023-03-10 03:14 UTC, jaywonchung commented
I think I get what's wrong. Let me post a PR that amends this now.

2023-03-10 03:17 UTC, insujang commented
Does that mean Zeus should also have arXiv link for now? I approved this since I saw Zeus also has its own PDF uploaded so that arXiv link should only be applied when the paper has explicitly been tagged as an arXiv paper, not ones accepted but not alive.

2023-03-10 03:18 UTC, jaywonchung commented
This one's my bad. The PDF up on Zeus is actually the camera ready version we submitted to NSDI, so it'll never change.

2023-03-10 03:22 UTC, insujang commented
Oh okay. My applogies for the confusion.

2023-03-10 03:23 UTC, mosharaf commented
Thanks both of you. The arxiv version and camera-ready version of a paper may or may not be the same. So it's better to keep them separate

2023-03-10 03:24 UTC, mosharaf commented
For example, Oort is a good example. Arxiv one is a super set of OSDI version.