Propose OSS page
SymbioticLab/SymbioticLab.github.io pull request #282
Opened 2024-10-26 22:28 UTC by majunze2001

Supported features:
- Display both GitHub projects and non-GitHub projects. GitHub projects will display the repo details including language, the number of forks, and the number of stars fetched from the GitHub API.
- Supports optional project logo.
- Supports organizing projects into subsections with separate descriptions. 

See `source/oss/index.md` for details.

2024-11-02 01:51 UTC, jaywonchung commented
A screenshot would be helpful. Also, there is placeholder text in the body of the page, so I don't think this PR is intended to be merged yet.

2024-11-21 12:36 UTC, mosharaf commented
@majunze2001 Can you please restart this?

2025-03-18 19:54 UTC, jaywonchung commented
<img width="1132" alt="Screenshot 2025-03-18 at 3 50 39 PM" src="https://github.com/user-attachments/assets/c4255f57-6490-42d6-aea7-30f744e467b7" />
@mosharaf This is what is looks now. Project descriptions are based on their GitHub repo description. Please let us know the projects you'd like to have on the final page and I'll add those.

2025-03-18 20:16 UTC, mosharaf commented
I was just typing why the two boxes with and without icons have texts misaligned :)

2025-03-18 20:17 UTC, mosharaf commented
This looks very good for a start! Great work @majunze2001 @jaywonchung

2025-03-18 20:22 UTC, mosharaf commented on source/open-source/index.md
> +    description: "Combining AI with traditional systems research."
This sounds more like AI for systems than systems for AI. I know we wanted to use Systems + AI to keep the door open, but I think we're mostly systems for AI.

2025-03-18 20:22 UTC, mosharaf commented on source/open-source/index.md
> +        description: "A resilient distributed training framework"
Missing .

2025-03-18 20:23 UTC, mosharaf commented on source/open-source/index.md
> +        description: "Build, train, and run your own multimodal model"
Missing .

2025-03-18 20:23 UTC, mosharaf commented on source/open-source/index.md
> +        description: "A scalable and extensible federated learning platform"
Same

2025-03-18 20:24 UTC, mosharaf requested changes
Left some minor comments, but looks good otherwise. I think we can iterate over the projects to include and texts to have over time.

2025-03-18 20:38 UTC, mosharaf approved these changes
LGTM! 🚀

2025-03-18 20:44 UTC, merged